[env:Sammy_Board]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_REV=1
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
build_src_filter = -<MIDAS/> +<MotorBoard/>
lib_deps = 
    plerup/EspSoftwareSerial@^8.2.0 ; Software serial
    WiFi@2.0.0

[env:MIDAS_sustainer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts =
    pre:extra_script.py
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_DISABLE_HAL_LOCKS=1
    -std=gnu++2a
    -DIS_SUSTAINER
build_unflags =
    -std=gnu++11
build_src_filter = +<MIDAS/> -<MotorBoard/>
lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.8 ; GPS

[env:MIDAS_booster]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts =
    pre:extra_script.py
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_DISABLE_HAL_LOCKS=1
    -std=gnu++2a
    -DIS_BOOSTER
build_unflags =
    -std=gnu++11
build_src_filter = +<MIDAS/> -<MotorBoard/>
lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.8 ; GPS