motor_1_specifications: # pitch
  dead_zone: [0, 15]
  step_size: 1.8
  actuation_time: 1
motor_2_specifications: # yaw
  dead_zone: [160, 200]
  step_size: 1.8
  actuation_time: 1

# specify latitude and longitude of launch site
turret_position:
  latitude: 40.1020
  longitude: 88.2272