motor_1_specifications: # pitch
  step_size: 1.8
  actuation_time: 1

motor_2_specifications: # yaw
  step_size: 1.8
  actuation_time: 1

K_list_1:
  Kp: 1
  Ki: 1
  Kd: 1

K_list_2:
  Kp: 1
  Ki: 1
  Kd: 1

# specify latitude and longitude of launch site
turret_position:
  latitude: 42.3809774
  longitude: -88.0901285
  altitude: 0

# From the first line of the untrimmed csv
rocket_position:
  latitude: 42.3758774
  longitude: -88.0969285
  altitude: 1600