motor_1_specifications: # pitch
  step_size: 1.8
  actuation_time: 1

motor_2_specifications: # yaw
  step_size: 1.8
  actuation_time: 1

K_list_1:
  Kp: 0.1
  Ki: 0.1
  Kd: 0.1

K_list_2:
  Kp: 0.1
  Ki: 0.1
  Kd: 0.1

# specify latitude and longitude of launch site
turret_position:
  latitude: 42.3809774
  longitude: -88.0901285
  altitude: 0

# From the first line of data_clean
rocket_position:
  latitude: 42.3762741
  longitude: -88.0944745
  altitude: 0 #1651.07
