motor_specs_pitch:
  step_size: 1.8
  gear_ratio: 0.242424242424
  actuation_time: 1

motor_specs_yaw:
  step_size: 1.8
  gear_ratio: 0.214285714286
  actuation_time: 1

K_list_pitch:
  Kp: 1
  Ki: 0.0
  Kd: 0.0

K_list_yaw:
  Kp: 1
  Ki: 0.0
  Kd: 0.0

# specify latitude and longitude of launch site
turret_position:
  latitude: 42.3809774
  longitude: -88.0901285
  altitude: 0

# From the first line of data_clean
rocket_position:
  latitude: 42.3762741
  longitude: -88.0944745
  altitude: 0 #1651.07
